################################

GET localhost:6969/guilds

################################

GET localhost:6969/members?gid=647e4611bad0e62d2ad4252b

################################

GET localhost:6969/guild?player_id=2

################################

POST localhost:6969/guilds/new
Content-Type: application/json

{
    "name": "MyGuild",
    "description": "Best guild ever",
    "limit_members": 20,
    "player_id": 1,
    "player_name": "alorthius"
}

################################

POST localhost:6969/guilds/members/new
Content-Type: application/json

{
    "gid": "647e4611bad0e62d2ad4252b",
    "player_id": 1,
    "player_name": "alorthius"
}

################################

DELETE localhost:6969/guilds/leave?gid=647e4611bad0e62d2ad4252b&player_id=1
Content-Type: application/json

################################

DELETE localhost:6969/guilds/delete?gid=647e4611bad0e62d2ad4252b

################################
