################################

GET localhost:6969/guilds

################################

POST localhost:6969/guilds/new
Content-Type: application/json

{
    "name": "MyGuild",
    "description": "Best guild ever",
    "limit_members": 20,
    "player_id": 1,
    "player_name": "alorthius"
}

################################

POST localhost:6969/guilds/647e3ea7ef9beabc494b9450/members/4
Content-Type: application/json

{
    "gid": "647e3ea7ef9beabc494b9450",
    "player_id": 4,
    "player_name": "alorthius"
}

################################

DELETE localhost:6969/guilds/647e3ea7ef9beabc494b9450/members/4
Content-Type: application/json

{
    "gid": "647e3ea7ef9beabc494b9450",
    "player_id": 4,
    "player_name": "alorthius"
}

################################

GET localhost:6969/members/647e3ea7ef9beabc494b9450

################################

DELETE localhost:6969/guilds/647e3ea7ef9beabc494b9450/