################################

GET localhost:9000/guilds?limit=1

################################

GET localhost:9000/members?gid=647f048d9b7738c9ed41bb31

################################

GET localhost:9000/guild?player_id=1

################################

POST localhost:9000/guilds/new
Content-Type: application/json

{
    "name": "MyGuild",
    "description": "Best guild ever",
    "limit_members": 20,
    "player_id": 2,
    "player_name": "alorthius"
}

################################

POST localhost:9000/guilds/members/new
Content-Type: application/json

{
    "gid": "647f04aa9b7738c9ed41bb33",
    "player_id": 1,
    "player_name": "alorthius"
}

################################

DELETE localhost:9000/guilds/leave?gid=647f048d9b7738c9ed41bb31&player_id=2
Content-Type: application/json

################################

DELETE localhost:9000/guilds/delete?gid=647f04aa9b7738c9ed41bb33

################################
