version: "3"

networks:
  hunters-game-network:
    driver: bridge
   
services:
  register-service:
    container_name: "register-service"
    build:
      context: RegisterService
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      hunters-game-network:
    depends_on:
      postgresql:
        condition: service_healthy

  login-service:
    container_name: "login-service"
    build:
      context: LoginService
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    networks:
      hunters-game-network:
    depends_on:
      postgresql:
        condition: service_healthy

  validation-service:
    container_name: "validation-service"
    build:
      context: ValidationService
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    networks:
      hunters-game-network:
    depends_on:
      postgresql:
        condition: service_healthy


  postgresql:
    container_name: "postgresql"
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "users"]
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - hunters-game-network
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql


  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    ports:
      - "82:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    depends_on:
      - postgresql
    links:
      - postgresql
    networks:
      - hunters-game-network
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
 pgadmin-data:
