version: "3"

networks:
  register:
    driver: bridge

services:
  register-service:
    build:
      context: RegisterService
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      register:
    depends_on:
      postgresql:
        condition: service_healthy
  login-service:
    build:
      context: LoginService
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    networks:
      register:
    depends_on:
      postgresql:
        condition: service_healthy

  validation-service:
    build:
      context: ValidationService
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    networks:
      register:
    depends_on:
      postgresql:
        condition: service_healthy


  postgresql:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "users"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - register
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql


  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    ports:
      - "82:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    depends_on:
      - postgresql
    links:
      - postgresql
    networks:
      - register
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
 pgadmin-data:
