POST localhost:8080/user
Content-Type: application/json

{
  "username": "dude1",
  "password": "dude"
}


###
POST localhost:8081/login/user
Content-Type: application/json

{
  "username": "dude1",
  "password": "dude"
}

###
POST localhost:8082/validate
Content-Type: application/json

{
  "uid": 1,
  "token": "ded269f30a49d5410c3c51698bd699aeb8813425"
}


###

POST localhost:8080/user
Content-Type: application/json

{
  "username": "dude1",
  "password": "dude"
}

###

GET localhost:8080/user/1